#!/usr/bin/ksh

# Special script for building ruby from a github tree.
# Assumes a lot...

#full_path=http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p194.tar.bz2
#suffix=.tar.bz2
#package_name=${full_path##*/}
export basedir_bit=ruby-github-pedz

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

#cd ${image_dir}
#if [[ ! -r "${package_name}" ]] ; then
#  wget ${full_path}
#fi

# Put in prvm/${basedir_bit} directory
export DEFAULT_PREFIX="${PUBLIC_BASE}/prvm/${basedir_bit}"

mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Configure --enable-shared &&
  Make &&
  Test &&
  Package &&
  Install
