#!/usr/bin/ksh

export basedir_bit=wget-1.13.4
suffix=tar.gz

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

cd ${image_dir}
if [[ ! -r "${basedir_bit}.${suffix}" ]] ; then
    wget http://ftp.gnu.org/gnu/wget/"${basedir_bit}.${suffix}"
fi

# The Check current has 6 failures.  I have not checked into why.
Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure --with-ssl=openssl &&
  Make &&
  Package &&
  Install
