#!/usr/bin/ksh
#
# From the web site:
# Libnettle is required to build GnuTLS. Libtasn1 is required, but an
# internal copy is included in case it is not installed on your system.
# The zlib library is not required but will be used if it is present on
# your system.
# pkg-config is also required.

# Should need to set only this variable
export full_path=ftp://ftp.gnutls.org/gcrypt/gnutls/v3.4/gnutls-3.4.16.tar.xz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# Setup can exit with 1 during debugging which will terminate this
# script
. "${build_scripts}/Setup"
mk_dir_structure

# 2 errors
#  Check &&

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure --with-included-libtasn1 --without-p11-kit &&
  Make &&
  Package &&
  Install
