#!/usr/bin/ksh

# Use this before you have a wget or openssl

export basedir_bit=wget-1.13

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

mkdir -p "${build_dir}"
cd "${build_dir}"

# The Check current has 6 failures.  I have not checked into why.
Unpack &&
  Patch &&
  Configure --without-ssl &&
  Make &&
  Package &&
  Install
