#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://ftp.gnu.org/gnu/wget/wget-1.18.tar.xz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# Setup can exit with 1 during debugging which will terminate this
# script
# Uncomment for packages that can not do out of tree builds
# export build=src
. "${build_scripts}/Setup"
mk_dir_structure

#  Check &&

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Package
