#!/usr/bin/ksh

full_path=http://ftp.gnu.org/gnu/texinfo/texinfo-4.13a.tar.gz
suffix=.tar.gz
package_name=${full_path##*/}
export basedir_bit=texinfo-4.13

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# 53 of 53 tests failed.
#  Check &&

Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Package &&
  Install
