#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.gz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${build_scripts}/Setup" ; then
    exit 1
fi
mk_dir_structure

export CFLAGS=-maix64
export OBJECT_MODE=64
#  --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no was
# added because I don't have the libraries compiled for them yet.

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no &&
  Make &&
  false &&
  Check &&
  Package &&
  Install
