#!/usr/bin/ksh

export basedir_bit=nettle-2.2

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_log_dir

mkdir -p "${build_dir}"
cd "${build_dir}"

Unpack &&
  Configure &&
  Make &&
  Check &&
  Package &&
  Install
