#!/usr/bin/ksh

full_path=http://git-core.googlecode.com/files/git-1.7.7.tar.gz
suffix=.tar.gz
package_name=${full_path##*/}
export basedir_bit=${package_name%${suffix}}
export build=src

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

  # Can't test without Python it seems.
  # Test &&

Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make NO_PYTHON=YesPlease &&
  Package NO_PYTHON=YesPlease &&
  Install
