#!/usr/bin/ksh
#
# From the web site:
# Libnettle is required to build GnuTLS. Libtasn1 is required, but an
# internal copy is included in case it is not installed on your system.
# The zlib library is not required but will be used if it is present on
# your system.
# pkg-config is also required.

export basedir_bit=gnutls-2.12.8

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_log_dir

mkdir -p "${build_dir}"
cd "${build_dir}"

Unpack &&
  Configure &&
  Make &&
  Test &&
  Package &&
  Install
