#!/usr/bin/ksh

# Should need to set only this variable
full_path=ftp://alpha.gnu.org/gnu/emacs/pretest/emacs-24.1-rc.tar.gz

package_name="${full_path##*/}"
a="${package_name%.gz}"
a="${a%.bz2}"
a="${a%.xz}"
a="${a%.tar}"
a="${a%-rc}"
export basedir_bit="$a"
unset a

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Check &&
  Package &&
  Install
