#!/usr/bin/ksh

full_path=http://ftp.ruby-lang.org/pub/ruby/snapshot.tar.gz
suffix=.tar.gz
package_name=${full_path##*/}
export basedir_bit=${package_name%${suffix}}

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Put in prvm/${basedir_bit} directory
export DEFAULT_PREFIX="${PUBLIC_BASE}/prvm/${basedir_bit}"

Unpack &&
  Patch &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Configure --enable-shared &&
  Make &&
  Test &&
  Package &&
  Install
