#!/usr/bin/ksh

export basedir_bit=patch-2.6.1

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

cd ${image_dir}
if [[ ! -r $( echo "${basedir_bit}".* ) ]] ; then
  wget http://mirrors.kernel.org/gnu/patch/${basedir_bit}.tar.gz
fi

Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Check &&
  Package &&
  Install
