#!/usr/bin/ksh

function fix_lib
{
  (
      cd ${dest_dir}${PUBLIC_BASE}/lib
      cp libcrypto.so shr.o
      ar r *crypto.a shr.o
      rm -f shr.o
      cp libssl.so shr.o
      ar r *ssl.a shr.o
      rm -f shr.o
  )
}

# Should need to set only this variable
export full_path=https://www.openssl.org/source/openssl-1.0.1t.tar.gz
export PUBLIC_BASE="/shared/pedzan/ruby-2.2.3"
export host_area="/blue-diamond/normal"

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# Setup can exit with 1 during debugging which will terminate this
# script
. "${build_scripts}/Setup"
mk_dir_structure

# Test &&
Unpack &&
  cd "${src_dir}" &&
  ./config --prefix=${PUBLIC_BASE} --openssldir=${PUBLIC_BASE}/lib/openssl --shared &&
  Make &&
  Package INSTALL_PREFIX=${dest_dir} &&
  fix_lib &&
  Install
