#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://www.openssl.org/source/openssl-1.0.1e.tar.gz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# Setup can exit with 1 during debugging which will terminate this
# script
. "${build_scripts}/Setup"
mk_dir_structure

Unpack &&
  cd "${src_dir}" &&
  ./config --prefix=${PUBLIC_BASE} --openssldir=${PUBLIC_BASE}/lib/openssl &&
  Make &&
  Test &&
  Package INSTALL_PREFIX=${dest_dir} &&
  Install
