#!/usr/bin/ksh

export basedir_bit=openssl-1.0.0e
export build=src

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_log_dir

cd ${image_dir}
if [[ ! -r "${basedir_bit}.tar.gz" ]] ; then
    wget "http://www.openssl.org/source/${basedir_bit}.tar.gz"
fi

Unpack &&
  cd "${src_dir}" &&
  ./config --prefix=${PUBLIC_BASE} --openssldir=${PUBLIC_BASE}/lib/openssl &&
  Make &&
  Test &&
  Package INSTALL_PREFIX=${dest_dir} &&
  Install
