#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://xmlsoft.org/sources/libxml2-sources-2.9.2.tar.gz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# Setup can exit with 1 during debugging which will terminate this
# script
. "${build_scripts}/Setup"
mk_dir_structure

#  Check &&

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure --without-python &&
  Make &&
  Package &&
  Install
