#!/usr/bin/ksh

full_path=http://mirrors.kernel.org/gnu/gcc/gcc-4.5.2/gcc-4.5.2.tar.bz2
suffix=.tar.bz2
package_name=${full_path##*/}
export basedir_bit=${package_name%${suffix}}

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_log_dir

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

export LDFLAGS="-Wl,-bbigtoc"
Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure \
    "--with-gmp=${PUBLIC_BASE}" \
    "--with-mpfr=${PUBLIC_BASE}" \
    "--with-mpc=${PUBLIC_BASE}" \
    "--disable-nls" \
    "--enable-threads=aix" \
    "--with-libiconv-prefix=/usr" \
    "--enable-__cxa_atexit" \
    "--enable-languages=c,c++"
  Make &&
  Package &&
  Install
