#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://ftp.gnu.org/gnu/less/less-451.tar.gz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# Setup can exit with 1 during debugging which will terminate this
# script
. "${build_scripts}/Setup"
mk_dir_structure

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Check &&
  Package &&
  Install
