#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.2d.tar.gz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${build_scripts}/Setup" ; then
    exit 1
fi
mk_dir_structure

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Check &&
  Package &&
  Install
