#!/usr/bin/ksh

full_path=http://ftp.gnu.org/gnu/gdb/gdb-7.3.1.tar.bz2
suffix=.tar.bz2
package_name=${full_path##*/}
export basedir_bit=${package_name%${suffix}}

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_log_dir

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# Doesn't pass (yet)
#  Check &&

Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure --enable-werror=no &&
  Make MAKEINFO=true &&
  Package &&
  Install
