#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://www.kernel.org/pub/software/scm/git/git-2.10.2.tar.xz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  if ! wget --no-check-certificate ${full_path} ; then
    echo "wget of ${full_path} failed" 1>&2
    exit 1
  fi
fi

# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )"
echo "basedir is ${basedir_bit}"

# Setup can exit with 1 during debugging which will terminate this
# script
export build=src
. "${build_scripts}/Setup"
mk_dir_structure

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make NO_PYTHON=YesPlease &&
  Package NO_PYTHON=YesPlease &&
  Install
