#!/usr/bin/ksh

# Note.  I'm trying to build expact, apr, apr-util, and pcre before
# building this.  If you build this first, it dies when it tries to
# package it because the needed libraries are not installed.

full_path=http://mirrors.ibiblio.org/apache/httpd/httpd-2.2.21.tar.bz2
suffix=.tar.bz2
package_name=${full_path##*/}
export basedir_bit=${package_name%${suffix}}

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_log_dir

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# NOTE -- next type use DEFAULT_PREFIX instead of this tap dance
# apr, apr-util, and httpd have a unique idea of prefix
ORIG_PUBLIC_BASE=${PUBLIC_BASE}
export PUBLIC_BASE="${PUBLIC_BASE}/apache2"

Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure \
  --with-apr=${PUBLIC_BASE} \
  --with-apr-util=${PUBLIC_BASE} \
  --with-pcre=${ORIG_PUBLIC_BASE} &&
  Make &&
  Test &&
  Package &&
  Install
