#!/usr/bin/ksh

# A brain dead script that just calls Configure, Make, Check, Package,
# Install.  Arguments passed into script are passed to Configure.

if [[ "$1" == '--nocheck' ]] ; then
  nocheck="$1"
  shift
else
  nocheck=""
fi

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi

"${build_scripts}/Unpack" &&
  "${build_scripts}/Patch" &&
  "${build_scripts}/Configure" "$@" &&
  "${build_scripts}/Make" &&
  "${build_scripts}/Check" ${nocheck} &&
  "${build_scripts}/Package" &&
  "${build_scripts}/Install"
