#!/usr/bin/ksh

# Should need to set only this variable
export full_path=http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.14.tar.gz

. "${0%/*}/BaseSetup"

# basename of what we are going to fetch
export package_name="${full_path##*/}"

# fetch the package
cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

export ABI=32
# Figure out what basedir this will produce
export basedir_bit="$( get_basedir_bit "${package_name}" )-${ABI}bit"
echo "basedir is ${basedir_bit}"

if [[ "$ABI" -eq 64 ]] ; then
  export CFLAGS=-maix64
  export OBJECT_MODE=64
fi

# Setup can exit with 1 during debugging which will terminate this
# script
# Uncomment for packages that can not do out of tree builds
# export build=src
. "${build_scripts}/Setup"
mk_dir_structure

#  Check &&

Unpack &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Package &&
  false &&
  Install
