#!/usr/bin/ksh

full_path=http://ftp.gnu.org/gnu/coreutils/coreutils-8.13.tar.gz
suffix=.tar.gz
package_name=${full_path##*/}
export basedir_bit=${package_name%${suffix}}

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

cd ${image_dir}
if [[ ! -r "${package_name}" ]] ; then
  wget ${full_path}
fi

# NOTE this is a special case.  We move prefix to the normal prefix
# plus /coreutils so that the executables are out of the main path.  We
# will then add symbolic links to get to the few commands that we want to
# get to by default.

export DEFAULT_PREFIX="${DEFAULT_PREFIX}/coreutils"

# has two failures
#  Check &&

Unpack &&
  mkdir -p "${build_dir}" &&
  cd "${build_dir}" &&
  Patch &&
  Configure &&
  Make &&
  Package &&
  Install
