#!/usr/bin/env bash

# Script used after gmp has been built for 32 bit and 64 bit to create
# the combined library and header file.

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi

echo "This hasn't been ported yet"
exit 1

"${build_scripts}/Journal" "fix-gmp called"

rm -rf /tmp/temp
mkdir /tmp/temp
EXT=$( echo ${PUBLIC_BASE}/build/gmp*-32bit/.libs/libgmp.so.* | sed -e 's/.*libgmp\.//' )
cp ${PUBLIC_BASE}/build/gmp-*-32bit/.libs/libgmp.${EXT} /tmp/temp/libgmp32.${EXT}
cp ${PUBLIC_BASE}/build/gmp-*-64bit/.libs/libgmp.${EXT} /tmp/temp/libgmp64.${EXT}
cd /tmp/temp
ar -X32_64 cr libgmp.a libgmp*.${EXT}
rm ${PUBLIC_BASE}/lib/libgmp.a
cp libgmp.a ${PUBLIC_BASE}/lib
cd /
rm -rf /tmp/temp

diff -D __64BIT__ \
  ${PUBLIC_BASE}/build/gmp-*-32bit/gmp.h \
  ${PUBLIC_BASE}/build/gmp-*-64bit/gmp.h \
  > ${PUBLIC_BASE}/include/gmp.h
