#!/usr/bin/env bash

# Script used after mpc has been built for 32 bit and 64 bit to create
# the combined library and header file.

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
echo "This hasn't been ported yet"
exit 1

"${build_scripts}/Journal" "fix-mpc called"

rm -rf /tmp/temp
mkdir /tmp/temp
EXT=$( echo ${PUBLIC_BASE}/build/mpc-*-32bit/src/.libs/libmpc.so.* |
       sed -e 's/.*libmpc\.//' )
cp ${PUBLIC_BASE}/build/mpc-*-32bit/src/.libs/libmpc.${EXT} /tmp/temp/libmpc32.${EXT}
cp ${PUBLIC_BASE}/build/mpc-*-64bit/src/.libs/libmpc.${EXT} /tmp/temp/libmpc64.${EXT}
cd /tmp/temp
ar -X32_64 cr libmpc.a libmpc*.${EXT}
rm ${PUBLIC_BASE}/lib/libmpc.a
cp libmpc.a ${PUBLIC_BASE}/lib
cd /
rm -rf /tmp/temp
