#!/usr/bin/ksh

# This script is called after Package and goes to the dest_dir,
# verifies that there are not going to be any collisions, and then
# copies via tar the dest_dir to the prefix dir.

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_log_dir

if [[ -r "${DONE}" ]] ; then
    exit 0
fi

"${build_scripts}/Journal" "${prog} called with '$@'"

(
    cd "${dest_dir}"

    # This doesn't actually do anything but print out files we are
    # replacing.
    find . -type f -print | ( cd / ; xargs ls 2> /dev/null )

    # NOTE!!!! This does not install any files that are not down the
    # PUBLIC_BASE path.
    cd "${dest_dir}${PUBLIC_BASE}"
    tar cf - . | ( mkdir -p "${PUBLIC_BASE}" && cd "${PUBLIC_BASE}" && tar xf - )
    echo $?
) | tee "${LOG}"

script_done
exit "${rc}"
