#!/usr/bin/env bash

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi

JOURNAL="${build_scripts}/journal.log"
NOW=$( date +%Y%m%d%H%M%S )
MYENV="$( env | egrep '^(ABI|CC|CC_FOR_BUILD|CFLAGS|CPP|CPPFLAGS|CPP_FOR_BUILD|CXX|CXXCPP|CXXFLAGS|F77|FFLAGS|LDFLAGS|LIBPATH|LIBS|M4|OBJECT_MODE|PWD|YACC|YFLAGS)=' )"

cat << EOF >> "${JOURNAL}"

*** Journal entry at $NOW ***
$MYENV
$@
EOF
