#!/usr/bin/ksh

# A script that patches the src directory

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

if [[ -r "${DONE}" ]] ; then
    exit 0
fi

"${build_scripts}/Journal" "${prog} called with '$@'"
(
    echo ${prog} called with "'$@'"
    if [[ -r "${work}/patches/${basedir}" ]] ; then
	echo Patching with "${work}/patches/${basedir}"
	cd "${src_dir}"
	patch -p1 < "${work}/patches/${basedir}"
	echo $?
    else
	echo Nothing to patch
        echo $?
    fi
) | tee "${LOG}"

script_done
exit "${rc}"
