#!/usr/bin/ksh

# A script that unpacks from images into the src directory.

# The if gives us a way to terminate the script if we are debugging
# Setup by having Setup exit with a non-zero status.
if ! . "${0%/*}/Setup" ; then
    exit 1
fi
mk_dir_structure

if [[ -r "${DONE}" ]] ; then
    exit 0
fi

"${build_scripts}/Journal" "${prog} called with '$@'"
(
    echo ${prog} called with "'$@'"
    if [[ "${package_name}x" != "x" ]] ; then
	pkg="${package_name}"
    else
	pkg=$( cd "${image_dir}"; echo "${basedir}."* )
    fi
    if [[ ! -d "${src_dir}" ]] ; then
	if [[ ! -d "${src_dir_base}" ]] ; then
	    mkdir -p "${src_dir_base}"
	fi
	cd "${src_dir_base}"
	echo Unpacking "${pkg} into ${src_dir_base}"
	case "${pkg}" in
	*.tgz)
	    ( cd "${image_dir}"; gunzip < "${pkg}" ) | tar xf -
	    ;;
	*.tar.gz)
	    ( cd "${image_dir}"; gunzip < "${pkg}" ) | tar xf -
	    ;;
	*.tar.bz2)
	    ( cd "${image_dir}"; bunzip2 < "${pkg}" ) | tar xf -
	    ;;
	*.tar.xz)
	    ( cd "${image_dir}"; unxz < "${pkg}" ) | tar xf -
	    ;;
	*.tar.lz)
	    ( cd "${image_dir}"; lzip -d < "${pkg}" ) | tar xf -
	    ;;
	*)
	    echo "Don't know how to unpack '${pkg}'" 1>&2
	    exit 1
	esac
    fi

    echo $?
) | tee "${LOG}"

script_done
exit "${rc}"
